"""Builds the Right-Click Exchange panel skin for the d3d9 proxy from Desktop\\uifler\\re_rightclickexchange.uif.

Only the main panel (Base_PacketExchange) is used: background frame + 25 reward cells (grp_bg), coupon slot
(base_item), title, Exchange / Close buttons. Texture loading (game UI pack, NTF v3/v7) is shared with
build_cr_assets.py. Output: rce_ui\\*.pus + rce_layout.h.
Usage: python build_rce_assets.py [uif] [gameDir]
"""
import struct, sys, os, hashlib
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
UIF = sys.argv[1] if len(sys.argv) > 1 else os.path.expandvars(r'%USERPROFILE%\Desktop\uifler\re_rightclickexchange.uif')
GAME = sys.argv[2] if len(sys.argv) > 2 else r'D:\NTTGame\KnightOnlineEn - Kopya'
FALLBACK_DIRS = [r'D:\25xxacs_2\Release\HSACSX\UI', r'D:\K2_Network\UI']
OUT = os.path.join(HERE, 'rce_ui')

# texture loader from build_cr_assets.py (the "textures" section only)
_cr = open(os.path.join(HERE, 'build_cr_assets.py'), encoding='utf-8').read()
_a = _cr.index('# ------------------------------------------------------------------ textures')
_b = _cr.index('# ------------------------------------------------------------------ build')
exec(compile(_cr[_a:_b], 'build_cr_assets.py', 'exec'))

# ------------------------------------------------------------------ UIF
TYPES = {0: 'BASE', 1: 'BUTTON', 2: 'STATIC', 3: 'PROGRESS', 4: 'IMAGE', 5: 'SCROLLBAR', 6: 'STRING',
         7: 'TRACKBAR', 8: 'EDIT', 9: 'AREA', 10: 'TOOLTIP', 11: 'ICON'}
d = open(UIF, 'rb').read()
o = 0
def I():
    global o; v = struct.unpack_from('<i', d, o)[0]; o += 4; return v
def U():
    global o; v = struct.unpack_from('<I', d, o)[0]; o += 4; return v
def F():
    global o; v = struct.unpack_from('<f', d, o)[0]; o += 4; return v
def S():
    global o; n = I(); v = d[o:o + n].decode('cp1252', 'replace'); o += n; return v

def elem(typ):
    e = {'type': TYPES[typ], 'name': S()}
    e['children'] = [elem(I()) for _ in range(I())]
    e['id'] = S(); e['rect'] = [I() for _ in range(4)]; [I() for _ in range(4)]; U(); U(); S(); S(); S()
    t = e['type']
    if t == 'IMAGE': e['tex'] = S(); e['uv'] = [F() for _ in range(4)]; F()
    elif t == 'STRING': e['font'] = S(); e['fontH'] = I(); U(); e['color'] = U(); e['text'] = S()
    elif t == 'BUTTON': [I() for _ in range(4)]; S(); S()
    elif t == 'STATIC': S()
    elif t == 'PROGRESS': F(); I(); I()
    elif t == 'AREA': I()
    return e

S(); nroot = I()                       # root: name + child count
PANEL = elem(I())                      # first child = Base_PacketExchange (the rest is the generator dialog)
assert PANEL['id'] == 'Base_PacketExchange', PANEL['id']

def find(e, id_):
    if e['id'] == id_: return e
    for k in e['children']:
        f = find(k, id_)
        if f: return f
def imgs(e, deep=False):
    out = []
    for k in e['children']:
        if k['type'] == 'IMAGE' and k.get('tex'): out.append(k)
        if deep: out += imgs(k, True)
    return out

# ------------------------------------------------------------------ build
os.makedirs(OUT, exist_ok=True)
bg = imgs(find(PANEL, 'grp_bg'))
L, T, R_, B = bbox(bg)
sprites = []
def add(name, images, rect=None):
    rect = rect or bbox(images)
    save_pus(compose(images, rect), name)
    sprites.append((name, rect))

add('bg', bg)
add('coupon', imgs(find(PANEL, 'grp_selected'), True)[:1])
for bid, short in (('btn_exchange', 'exchange'), ('btn_close', 'close')):
    st = imgs(find(PANEL, bid))
    for si, sn in enumerate(('n', 'd', 'o')):
        add('%s_%s' % (short, sn), [st[si]])
prev = bg + imgs(find(PANEL, 'grp_selected'), True)[:1] + [imgs(find(PANEL, 'btn_exchange'))[0], imgs(find(PANEL, 'btn_close'))[0]]
compose(prev, [L, T, R_, B]).save(os.path.join(OUT, '_preview.png'))

def rs(r): return '{ %d, %d, %d, %d }' % (r[0] - L, r[1] - T, r[2] - L, r[3] - T)
title = find(PANEL, 'txt_title')
with open(os.path.join(HERE, 'rce_layout.h'), 'w') as f:
    f.write('// Generated by build_rce_assets.py from re_rightclickexchange.uif -- do not edit by hand.\n#pragma once\n')
    f.write('#ifndef RCE_TYPES\n#define RCE_TYPES\nstruct RceRect { int l, t, r, b; };\nstruct RceSprite { const char* name; RceRect rc; };\n#endif\n')
    f.write('static const int RCE_W = %d, RCE_H = %d;\n' % (R_ - L, B - T))
    f.write('static const int RCE_SLOT_COUNT = 25;\n')
    f.write('static const RceSprite RCE_SPRITES[] = {\n')
    for n, r in sprites:
        f.write('    { "%s", %s },\n' % (n, rs(r)))
    f.write('};\n')
    f.write('static const RceRect RCE_COUPON = %s;\n' % rs(find(PANEL, 'base_item')['rect']))
    f.write('static const RceRect RCE_TITLE = %s;  // %s h%d color %08X\n' % (rs(title['rect']), title['font'], title['fontH'], title['color']))
    f.write('static const RceRect RCE_BTN_EXCHANGE = %s;\n' % rs(find(PANEL, 'btn_exchange')['rect']))
    f.write('static const RceRect RCE_BTN_CLOSE = %s;\n' % rs(find(PANEL, 'btn_close')['rect']))
    f.write('static const RceRect RCE_SLOTS[25] = {\n')
    for i in range(1, 26):
        f.write('    %s,\n' % rs(find(find(PANEL, 'item_%d' % i), 'area_slot')['rect']))
    f.write('};\n')
print('sprites', len(sprites), 'panel', R_ - L, 'x', B - T, '->', OUT)
