r"""Drop button (chest) + compact drop list next to the target bar (drop_button.cpp), from the game's own art:
  - chest:  the "Dragon Box" item icon (ITEM 810341000 -> itemicon_8_1034_10_0.dxt), small; brighter for hover
  - frame:  the green message box (ui\re_message_box.dxt, kopanel.green_frame)
  - cells:  the loot window's item cell (re_droppeditem.uif, ui\re_warp_list_2.dxt)
  - close:  the coin shop's close button (re_eventcoin.uif "close", ui\re_skill04.dxt)
Output: dropbtn_ui\chest_n.pus, chest_o.pus, mini_bg.pus, cell.pus, close_n/o/d.pus + dropbtn_layout.h"""
import os, ntpath
from PIL import Image, ImageEnhance
import kopanel as K
import uif3

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, 'dropbtn_ui')

def img_of(e, size=None):
    T = K.tex(ntpath.basename(e['tex'])); W_, H_ = T.size; u0, v0, u1, v1 = e['uv']; l, t, r, b = e['rect']
    return T.crop((round(u0 * W_), round(v0 * H_), round(u1 * W_), round(v1 * H_))).resize(size or (r - l, b - t), Image.LANCZOS)

def find(root, id_):
    for e in root['children']:
        if e.get('id') == id_: return e
        if e.get('children'):
            f = find(e, id_)
            if f: return f
    return None

os.makedirs(OUT, exist_ok=True)

# chest button
CH = 30
icon = K.load_tex(K._icon_file(81034100)).convert('RGBA').crop((0, 0, 45, 45)).resize((CH, CH), Image.LANCZOS)
K.save_pus(icon, os.path.join(OUT, 'chest_n.pus'))
K.save_pus(ImageEnhance.Brightness(icon).enhance(1.35), os.path.join(OUT, 'chest_o.pus'))

# compact list: 6 x 4 loot cells (51 px pitch, as in the loot window) in the green frame
drop, _, _ = uif3.load(os.path.join(HERE, 'native_ui', 're_droppeditem.uif'))
cell = img_of(next(e for e in drop['children'] if e['type'] == 'IMAGE'))           # 55 x 55
K.save_pus(cell, os.path.join(OUT, 'cell.pus'))
COLS, ROWS, PITCH = 6, 4, 51
GX, GY = 18, 46                                                                     # grid origin
W = GX * 2 + COLS * PITCH + 4
H = GY + ROWS * PITCH + 4 + 30
bg = K.green_frame(W, H)
for r in range(ROWS):
    for c in range(COLS):
        bg.alpha_composite(cell, (GX + c * PITCH, GY + r * PITCH))
K.save_pus(bg, os.path.join(OUT, 'mini_bg.pus'))

coin, _, _ = uif3.load(os.path.join(HERE, 'native_ui', 're_eventcoin.uif'))
close = find(coin, 'close')
cimgs = [k for k in close['children'] if k['type'] == 'IMAGE']
CS = 26
for name, im in (('close_n', cimgs[0]), ('close_d', cimgs[1]), ('close_o', cimgs[2])):
    K.save_pus(img_of(im, (CS, CS)), os.path.join(OUT, name + '.pus'))

prev = bg.copy()
prev.alpha_composite(Image.open(os.path.join(OUT, 'close_n.png')), (W - CS - 12, 12))
prev.save(os.path.join(OUT, '_mini_preview.png'))
with open(os.path.join(HERE, 'dropbtn_layout.h'), 'w') as f:
    f.write('// Generated by build_dropmini_assets.py -- do not edit by hand.\n#pragma once\n')
    f.write('static const int DB_CHEST = %d;\n' % CH)
    f.write('static const int DM_W = %d, DM_H = %d, DM_COLS = %d, DM_ROWS = %d, DM_PITCH = %d, DM_GX = %d, DM_GY = %d;\n' % (W, H, COLS, ROWS, PITCH, GX, GY))
    f.write('static const int DM_TITLE[4] = { 22, 14, %d, 40 };\n' % (W - CS - 20))
    f.write('static const int DM_CLOSE[4] = { %d, 12, %d, %d };\n' % (W - CS - 12, W - 12, 12 + CS))
    f.write('static const int DM_INFO[4] = { 22, %d, %d, %d };\n' % (GY + ROWS * PITCH + 6, W - 22, H - 12))
print('drop mini ->', OUT, W, H)
