r"""Re-Connect window skin (reconnect.cpp), the same as the reference picture F:\resimlers\resimlers\re-connect.png:
the game's own message box re_msgboxokcancel.uif (atlas ui\re_message_box.dxt: green frame with bronze corners,
dark buttons with a gold edge). Title 'Reconnecting to the server' (orange), text, Reconnect / Exit.
Output: reconnect_ui\*.pus + reconnect_layout.h
"""
import os, ntpath
from PIL import Image
import kopanel as K
import uif3

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, 'reconnect_ui')
root, _, _ = uif3.load(os.path.join(HERE, 'native_ui', 're_msgboxokcancel.uif'))

def img_of(e):
    T = K.tex(ntpath.basename(e['tex'])); W_, H_ = T.size; u0, v0, u1, v1 = e['uv']; l, t, r, b = e['rect']
    return T.crop((round(u0 * W_), round(v0 * H_), round(u1 * W_), round(v1 * H_))).resize((r - l, b - t), Image.LANCZOS)

W, H = 356, 198
bg = Image.new('RGBA', (W, H), (0, 0, 0, 0))
bg.alpha_composite(Image.new('RGBA', (W - 16, H - 16), (14, 19, 15, 238)), (8, 8))   # the box interior is dark in the game
btn = {}
for e in root['children']:
    if e['type'] == 'IMAGE': bg.alpha_composite(img_of(e), tuple(e['rect'][:2]))
    elif e['type'] == 'BUTTON': btn[e['id']] = e
L = {}
def r(name, x0, y0, x1, y1): L[name] = (x0, y0, x1, y1)
r('title', 20, 16, W - 20, 40)
r('text', 26, 40, W - 26, 128)
r('btn_reconnect', *btn['btn_ok']['rect']); r('btn_exit', *btn['btn_cancel']['rect'])

os.makedirs(OUT, exist_ok=True)
K.save_pus(bg, os.path.join(OUT, 'bg.pus'))
# the button art has 'Confirm' painted on it: keep the caps, stretch the plain left part (states: normal, down, over)
imgs = [img_of(k) for k in btn['btn_ok']['children'] if k['type'] == 'IMAGE']
bw, bh = imgs[0].size
for st, im in (('n', imgs[0]), ('d', imgs[1]), ('o', imgs[2])):
    K.save_pus(K.slice3(im, bw, bh, 10, mid=(12, 22)), os.path.join(OUT, 'btn_%s.pus' % st))
prev = bg.copy()
for k in ('btn_reconnect', 'btn_exit'):
    prev.alpha_composite(Image.open(os.path.join(OUT, 'btn_n.png')).resize((L[k][2] - L[k][0], L[k][3] - L[k][1])), L[k][:2])
prev.save(os.path.join(OUT, '_preview.png'))
with open(os.path.join(HERE, 'reconnect_layout.h'), 'w') as f:
    f.write('// Generated by build_reconnect_assets.py -- do not edit by hand.\n#pragma once\n')
    f.write('static const int RC_W = %d, RC_H = %d;\n' % (W, H))
    for k, v in L.items():
        f.write('static const int RC_%s[4] = { %d, %d, %d, %d };\n' % ((k.upper(),) + tuple(v)))
print('reconnect skin ->', OUT)
