"""Castle Siege War board skin (csw_panel.cpp) from the game's own re_siege_warfare_challenge.uif.
The 2625 exe has no class that loads that uif, so the proxy draws the window: this renders the uif's images with
the game's textures (rows, close button and scrollbar left out) and writes the control rectangles.
Output: csw_ui\\*.pus + csw_layout.h.
Usage: python build_csw_assets.py [uif] [packDir]
  uif     plain re_siege_warfare_challenge.uif   (default: PatchTools\\uif_plain_20261004_0205 copy)
  packDir folder with a ui.hdr / ui.src whose .dxt are not HopeGuard-encrypted (default: PatchTools\\ui_pack_before_all_20261004)
"""
import os, sys, struct
from PIL import Image
import uifed, uifrender

HERE = os.path.dirname(os.path.abspath(__file__))
TOOLS = os.path.join(HERE, '..', '..', 'PatchTools')
UIF = sys.argv[1] if len(sys.argv) > 1 else os.path.join(TOOLS, 'uif_plain_20261004_0205', '1D2E0B6C_re_siege_warfare_challenge.uif')
PACK = sys.argv[2] if len(sys.argv) > 2 else os.path.join(TOOLS, 'ui_pack_before_all_20261004')
OUT = os.path.join(HERE, 'csw_ui')
OY = 1          # the top right frame piece starts at y = -1
ROWS = 20


class Tex(uifrender.Tex):
    def __init__(s):
        s.pack = {}; s.cache = {}
        h = open(os.path.join(PACK, 'ui.hdr'), 'rb').read(); o = 8
        while o < len(h):
            l = struct.unpack_from('<H', h, o)[0]; nm = h[o + 2:o + 2 + l].decode('cp1252', 'replace').lower()
            off, sz = struct.unpack_from('<II', h, o + 2 + l); o += 2 + l + 8; s.pack[nm] = (off, sz)
        s.src = open(os.path.join(PACK, 'ui.src'), 'rb')


tex = Tex()
root = uifed.load(UIF)

def kids(e): return [c for c in e.children if c.typ is not None]
def all_elems(e):
    for c in e.children:
        if c.typ is not None: yield c
        yield from all_elems(c)

def cut(e):
    img = tex.get(e.tex); W, H = img.size
    u0, v0, u1, v1 = e.uv
    l, t, r, b = e.rect
    part = img.crop((round(u0 * W), round(v0 * H), round(u1 * W), round(v1 * H)))
    return part if part.size == (r - l, b - t) else part.resize((r - l, b - t), Image.BILINEAR)

top = [e for e in all_elems(root)]
users = next(e for e in top if e.id == 'grp_users')
close = next(e for e in top if e.id == 'btn_close')
scroll = next(e for e in top if e.type == 'SCROLLBAR')
skip = set(id(x) for g in (users, close, scroll) for x in [g] + list(all_elems(g)))

images = [e for e in top if e.type == 'IMAGE' and id(e) not in skip and e.tex]
W = max(e.rect[2] for e in images + [close]) + 1
H = max(e.rect[3] for e in images) + OY + 1
frame = Image.new('RGBA', (W, H), (0, 0, 0, 0))
for e in images:
    l, t, r, b = e.rect
    if r > l and b > t:
        frame.alpha_composite(cut(e), (l, t + OY))

L = {}
def rc(name, r): L[name] = (r[0], r[1] + OY, r[2], r[3] + OY)

for e in top:
    if e.type != 'STRING' or id(e) in skip: continue
    txt = e.text or ''
    if txt == 'Participant Clans': rc('title', e.rect)
    elif txt == 'Rank': rc('h_rank', e.rect)
    elif txt == 'Icon': rc('h_icon', e.rect)
    elif txt == 'Clan': rc('h_clan', e.rect)
    elif txt == 'Kill': rc('h_kill', e.rect)
    elif txt == 'Barracks': rc('h_death', e.rect)
    elif txt.startswith('Remaining'): rc('foot_label', e.rect)
    elif e.id == 'txt_death': rc('foot_value', e.rect)

row0 = next(e for e in kids(users) if e.id == 'grp_user_0')
row1 = next(e for e in kids(users) if e.id == 'grp_user_1')
pitch = row1.rect[1] - row0.rect[1]
for c in kids(row0):
    rc('row_' + c.id.replace('txt_', '').replace('img_', ''), c.rect)
rc('close', close.rect)

os.makedirs(OUT, exist_ok=True)
def save_pus(img, name):
    img = img.convert('RGBA'); w, h = img.size
    px = bytearray()
    for r_, g, b, a in img.getdata():
        px += bytes((b * a // 255, g * a // 255, r_ * a // 255, a))
    with open(os.path.join(OUT, name + '.pus'), 'wb') as f:
        f.write(b'PUSI' + struct.pack('<II', w, h) + px)
    img.save(os.path.join(OUT, name + '.png'))

save_pus(frame, 'frame')
save_pus(cut(next(c for c in kids(row0) if c.id == 'img_myself_bg')), 'row_me')
states = [c for c in kids(close) if c.type == 'IMAGE']       # normal, down, on, disabled
for name, i in (('close_n', 0), ('close_d', 1), ('close_o', 2)):
    save_pus(cut(states[min(i, len(states) - 1)]), name)

prev = frame.copy()
prev.alpha_composite(Image.open(os.path.join(OUT, 'close_n.png')), L['close'][:2])
prev.alpha_composite(Image.open(os.path.join(OUT, 'row_me.png')), L['row_myself_bg'][:2])
bgp = Image.new('RGBA', prev.size, (60, 70, 60, 255)); bgp.alpha_composite(prev); bgp.save(os.path.join(OUT, '_preview.png'))

with open(os.path.join(HERE, 'csw_layout.h'), 'w') as f:
    f.write('// Generated by build_csw_assets.py from re_siege_warfare_challenge.uif -- do not edit by hand.\n#pragma once\n')
    f.write('static const int CWS_W = %d, CWS_H = %d, CWS_ROWS = %d, CWS_ROW_PITCH = %d;\n' % (W, H, ROWS, pitch))
    for k in sorted(L):
        f.write('static const int CWS_%s[4] = { %d, %d, %d, %d };\n' % ((k.upper(),) + L[k]))
print('csw skin ->', OUT, W, H, 'pitch', pitch, sorted(L))
