"""Event rewards panel skin (event_reward_panel.cpp): what BDW / Chaos / Juraid winners and losers get, shown
while the event signs up. Pieces of the game's atlas ui\\tournament_chaos_2021_a01.dxt (same as the lottery).
Output: evreward_ui\\*.pus + evreward_layout.h; item icons of EVENT_REWARDS -> ev_ui\\ (shared set).
Usage: python build_evreward_assets.py
"""
import os
from PIL import Image
import kopanel as K

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, 'evreward_ui')
T = K.tex('tournament_chaos_2021_a01.dxt')
FRAME     = K.piece(T, (333, 66, 444, 181))
PANELBG   = K.piece(T, (0, 858, 440, 916))      # brown textured bar with gold border: window body
GOLDFRAME = K.piece(T, (4, 26, 96, 120))
FIELD     = K.piece(T, (184, 26, 468, 66))
X = [K.piece(T, (182, 66, 216, 99)), K.piece(T, (216, 66, 250, 99)), K.piece(T, (250, 66, 284, 99))]
BAR = {k: K.piece(T, b) for k, b in {
    'red': (4, 425, 196, 495), 'pink': (4, 495, 196, 565), 'dark': (4, 565, 196, 637),
    'grey': (4, 637, 196, 707), 'green': (4, 707, 196, 777), 'blue': (4, 777, 196, 850)}.items()}

W = 248
ROWS = 3
L = {}
def r(name, x0, y0, x1, y1): L[name] = (x0, y0, x1, y1); return (x0, y0, x1, y1)

y = 20
r('time', 52, y, W - 52, y + 26); r('close_x', W - 44, y + 1, W - 20, y + 25)    # reference: time in the blue plate
y += 32
r('title', 12, y, W - 18, y + 30)                                               # event name box
y += 36
parts = []
for side in ('win', 'lose'):
    parts.append(('bar', r('%s_bar' % side, 12, y, W - 18, y + 22)))
    y += 26
    for i in range(ROWS):
        parts.append(('slot', r('%s_slot_%d' % (side, i), 22, y, 62, y + 40)))
        parts.append(('name', r('%s_name_%d' % (side, i), 68, y + 1, W - 22, y + 20)))
        parts.append(('count', r('%s_count_%d' % (side, i), 110, y + 22, W - 64, y + 38)))
        y += 44
    r('%s_info' % side, 12, y, W - 18, y + 16)
    y += 20
y += 2
r('close', W // 2 - 56, y, W // 2 + 56, y + 26)
H = y + 46

from PIL import ImageDraw
def dark_box(w, h, fill=(22, 20, 18, 250), edge=(120, 96, 52, 255), inner=(52, 44, 30, 255)):
    im = Image.new('RGBA', (w, h), fill); d = ImageDraw.Draw(im)
    d.rectangle((0, 0, w - 1, h - 1), outline=edge); d.rectangle((2, 2, w - 3, h - 3), outline=inner)
    return im
REDFRAME = Image.merge('RGBA', [c.point(f) for c, f in zip(GOLDFRAME.split(), (lambda v: min(255, int(v * 1.05)), lambda v: int(v * 0.32), lambda v: int(v * 0.3), lambda v: v))])
bg = K.green_frame(W, H)                         # the game's green message box frame (bronze corners)
def put(img, rect): bg.alpha_composite(img, rect[:2])
put(K.slice3(BAR['blue'], L['time'][2] - L['time'][0], 26, 14), L['time'])
put(dark_box(L['title'][2] - L['title'][0], 30, (26, 44, 40, 255), (90, 110, 96, 255), (40, 58, 52, 255)), L['title'])
for kind, rc in parts:
    w, h = rc[2] - rc[0], rc[3] - rc[1]
    lose = rc[1] >= L['lose_bar'][1]
    if kind == 'bar':    put(K.slice3(BAR['dark' if lose else 'grey'], w, h, 12), rc)
    elif kind == 'slot': put(K.slice9(REDFRAME if lose else GOLDFRAME, w, h, 10), rc)
    elif kind == 'name': put(K.slice3(FIELD, w, h, 8, mid=(20, 60)), rc)
    else:                put(K.slice3(BAR['green'], w, h, 10), rc)

os.makedirs(OUT, exist_ok=True)
K.save_pus(bg, os.path.join(OUT, 'bg.pus'))
cw, ch = L['close'][2] - L['close'][0], L['close'][3] - L['close'][1]
for st, key in (('n', 'red'), ('o', 'pink'), ('d', 'dark')):
    K.save_pus(K.slice3(BAR[key], cw, ch, 12), os.path.join(OUT, 'close_%s.pus' % st))
for st, img in zip(('n', 'o', 'd'), X):
    K.save_pus(K.fit(img, 24, 24), os.path.join(OUT, 'x_%s.pus' % st))
prev = bg.copy()
prev.alpha_composite(Image.open(os.path.join(OUT, 'close_n.png')), L['close'][:2])
prev.alpha_composite(Image.open(os.path.join(OUT, 'x_n.png')), L['close_x'][:2])
prev.save(os.path.join(OUT, '_preview.png'))

with open(os.path.join(HERE, 'evreward_layout.h'), 'w') as f:
    f.write('// Generated by build_evreward_assets.py -- do not edit by hand.\n#pragma once\n')
    f.write('static const int ER_W = %d, ER_H = %d, ER_ROWS = %d;\n' % (W, H, ROWS))
    for k, v in L.items():
        f.write('static const int ER_%s[4] = { %d, %d, %d, %d };\n' % ((k.upper(),) + v))

rows = K.sql('SELECT itemid1, itemid2, itemid3 FROM EVENT_REWARDS')
K.item_icons([int(x) for line in rows.splitlines() for x in line.split('|') if x.strip().isdigit()], os.path.join(HERE, 'ev_ui'))
print('event reward skin ->', OUT, W, H)
