"""Solo Cape catalog: builds Data\\Cloak.tbl (game table + solo rows) and the matching KNIGHTS_CAPE SQL.

Cape ID -> textures (client, decompile 0x8F5xxx): Cloak_C_%02d = id%10000%100, Cloak_M_%02d = id%10000/100.
Solo designs = the new textures from D:\\MURO\\SOLO CAPE (added to Item\\item.src by pack_add.py).
Rows: every design x pattern 0..16 (id = design + 100*pattern).
Usage: python build_solo_cloak.py <gameDir> <outSql>
"""
import struct, sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import kotbl

SOLO = [(55, 'Solo Crimson'), (56, 'Solo Flame'), (57, 'Solo Viking'), (58, 'Solo Demon'), (59, 'Solo Bronze'),
        (81, 'Solo Trabzonspor'), (82, 'Solo Fenerbahce'), (83, 'Solo Besiktas'), (84, 'Solo Galatasaray'),
        (85, 'Solo Blue Serpent'), (86, 'Solo Gold Serpent'), (87, 'Solo Flag'), (88, 'Solo Dragon Scale'),
        (89, 'Solo White Knight'), (90, 'Solo Shadow'), (91, 'Solo Royal Blue'), (92, 'Solo Midnight'),
        (93, 'Solo Crimson Velvet'), (94, 'Solo Ragged')]
PATTERNS = 17
DESC = 'Solo Cape | +300 HP, +5% Attack, +5% Defense'
FMT = {1: 'b', 2: 'B', 3: 'h', 4: 'H', 5: 'i', 6: 'I', 8: 'f', 9: 'd'}

def solo_rows():
    for c, name in SOLO:
        for m in range(PATTERNS):
            #       id           name  price dur grade loyalty ranking desc  type ticket
            yield [c + 100 * m, name, 0, 0, 0, 0, 12, DESC if m == 0 else '', 2, 0]

def main():
    game, out_sql = sys.argv[1], sys.argv[2]
    src = os.path.join(game, 'Data', 'Cloak.tbl')
    orig = src + '.before_solocape'
    if not os.path.exists(orig):
        open(orig, 'wb').write(open(src, 'rb').read())
    plain = kotbl.decrypt(open(orig, 'rb').read(), 'rev')
    prefix, d = plain[:5], plain[5:]
    o = 0
    nc = struct.unpack_from('<i', d, o)[0]; o += 4
    types = list(struct.unpack_from('<%di' % nc, d, o)); o += 4 * nc
    nr = struct.unpack_from('<i', d, o)[0]; o += 4
    body = d[o:]
    ids = set()
    # collect existing ids (col0) to avoid duplicates
    p = 0
    for _ in range(nr):
        ids.add(struct.unpack_from('<I', body, p)[0])
        for t in types:
            if t == 7: p += 4 + struct.unpack_from('<i', body, p)[0]
            else: p += struct.calcsize(FMT[t])
    assert p == len(body)
    new = bytearray()
    added = [r for r in solo_rows() if r[0] not in ids]
    for r in added:
        for t, v in zip(types, r):
            if t == 7:
                b = v.encode('cp1252'); new += struct.pack('<i', len(b)) + b
            else:
                new += struct.pack('<' + FMT[t], v)
    blob = struct.pack('<i', nc) + struct.pack('<%di' % nc, *types) + struct.pack('<i', nr + len(added)) + body + bytes(new)
    open(src, 'wb').write(kotbl.encrypt(prefix + blob, 'rev'))
    # self-check
    chk = kotbl.decrypt(open(src, 'rb').read(), 'rev')
    assert chk == prefix + blob
    print('Cloak.tbl rows', nr, '->', nr + len(added))

    with open(out_sql, 'w') as f:
        f.write('-- Solo Cape catalog (generated by build_solo_cloak.py)\n')
        f.write("DELETE FROM KNIGHTS_CAPE WHERE strName LIKE 'Solo %';\n")
        for r in solo_rows():
            f.write("INSERT INTO KNIGHTS_CAPE (sCapeIndex, strName, nBuyPrice, nDuration, byGrade, nBuyLoyalty, byRanking, Description, bType, bTicket, BonusType) "
                    "VALUES (%d, '%s', %d, %d, %d, %d, %d, '%s', %d, %d, 0);\n" % (r[0], r[1], r[2], r[3], r[4], r[5], r[6], r[7], r[8], r[9]))
    print('sql ->', out_sql)

if __name__ == '__main__':
    main()
