"""Lottery Event panel skin (lottery_panel.cpp), made from the game's own atlas ui\\tournament_chaos_2021_a01.dxt.
Layout = the reference picture: title plate + close, three red info rows (Time Left / Ticket Sold / Ticket),
required item slot + amount field + Buy, "Rewards" bar, four reward slots (1st..4th).
Output: lottery_ui\\*.pus + lottery_layout.h, item icons for every lottery item in ev_ui\\ (shared icon set).
Usage: python build_lottery_assets.py
"""
import os
from PIL import Image
import kopanel as K

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, 'lottery_ui')
T = K.tex('tournament_chaos_2021_a01.dxt')

# atlas cells (trimmed to their visible pixels)
FRAME     = K.piece(T, (333, 66, 444, 181))
PANELBG   = K.piece(T, (0, 858, 440, 916))      # brown textured bar with gold border: window body      # dark rounded panel, 9-slice
GOLDFRAME = K.piece(T, (4, 26, 96, 120))        # gold square frame (item slot)
FIELD     = K.piece(T, (184, 26, 468, 66))      # dark field with gold border
X = [K.piece(T, (182, 66, 216, 99)), K.piece(T, (216, 66, 250, 99)), K.piece(T, (250, 66, 284, 99))]
BAR = {k: K.piece(T, b) for k, b in {
    'red': (4, 425, 196, 495), 'pink': (4, 495, 196, 565), 'dark': (4, 565, 196, 637),
    'grey': (4, 637, 196, 707), 'green': (4, 707, 196, 777), 'blue': (4, 777, 196, 850)}.items()}
WIDE_BROWN = K.piece(T, (0, 860, 438, 914))

W, H = 230, 286
L = {}                                        # layout rects for the header
def r(name, x0, y0, x1, y1): L[name] = (x0, y0, x1, y1); return (x0, y0, x1, y1)

from PIL import ImageDraw
def dark_box(w, h, fill=(22, 20, 18, 250), edge=(120, 96, 52, 255), inner=(52, 44, 30, 255)):
    im = Image.new('RGBA', (w, h), fill); d = ImageDraw.Draw(im)
    d.rectangle((0, 0, w - 1, h - 1), outline=edge); d.rectangle((2, 2, w - 3, h - 3), outline=inner)
    return im
bg = dark_box(W, H)                              # reference: dark body, thin bronze border
def put(img, rect):
    x0, y0, x1, y1 = rect
    bg.alpha_composite(img, (x0, y0))

put(K.slice3(BAR['blue'], 150, 26, 14), r('title', 40, 8, 190, 34))
r('close', 198, 9, 222, 33)
for i, name in enumerate(('row_time', 'row_sold', 'row_ticket')):
    y = 42 + i * 25
    put(K.slice3(BAR['red'], W - 24, 23, 12), r(name, 12, y, W - 12, y + 23))
put(dark_box(W - 24, 50, (14, 13, 12, 255)), r('buy_box', 12, 120, W - 12, 170))
put(K.slice9(GOLDFRAME, 40, 40, 10), r('req_slot', 18, 125, 58, 165))
put(K.slice3(BAR['green'], 100, 24, 12), r('req_field', 62, 133, 162, 157))   # teal price field
r('buy', 166, 132, W - 18, 158)
put(K.slice3(BAR['grey'], W - 24, 24, 12), r('rewards_bar', 12, 176, W - 12, 200))
put(dark_box(W - 24, 64, (14, 13, 12, 255)), (12, 202, W - 12, 266))
for i in range(4):
    x = 20 + i * 50
    r('rank_%d' % i, x - 4, 204, x + 44, 218)
    put(K.slice9(GOLDFRAME, 40, 40, 10), r('reward_%d' % i, x, 220, x + 40, 260))
r('msg', 12, 264, W - 12, 280)

os.makedirs(OUT, exist_ok=True)
K.save_pus(bg, os.path.join(OUT, 'bg.pus'))
for st, key in (('n', 'red'), ('o', 'pink'), ('d', 'dark')):
    K.save_pus(K.slice3(BAR[key], L['buy'][2] - L['buy'][0], L['buy'][3] - L['buy'][1], 12), os.path.join(OUT, 'buy_%s.pus' % st))
for st, img in zip(('n', 'o', 'd'), (X[0], X[1], X[2])):
    K.save_pus(K.fit(img, 24, 24), os.path.join(OUT, 'close_%s.pus' % st))
# collapsed tab while the event runs (title plate art)
K.save_pus(K.slice3(BAR['blue'], 110, 26, 14), os.path.join(OUT, 'tab_n.pus'))
K.save_pus(K.slice3(BAR['green'], 110, 26, 14), os.path.join(OUT, 'tab_o.pus'))

prev = bg.copy()
prev.alpha_composite(Image.open(os.path.join(OUT, 'buy_n.png')), L['buy'][:2])
prev.alpha_composite(Image.open(os.path.join(OUT, 'close_n.png')), L['close'][:2])
prev.save(os.path.join(OUT, '_preview.png'))

with open(os.path.join(HERE, 'lottery_layout.h'), 'w') as f:
    f.write('// Generated by build_lottery_assets.py -- do not edit by hand.\n#pragma once\n')
    f.write('static const int LT_W = %d, LT_H = %d, LT_TAB_W = 110, LT_TAB_H = 26;\n' % (W, H))
    for k, v in L.items():
        f.write('static const int LT_%s[4] = { %d, %d, %d, %d };\n' % ((k.upper(),) + v))

# icons of every item a lottery can ask for or give (shared set in ev_ui)
rows = K.sql('SELECT reqItem1,reqItem2,reqItem3,reqItem4,reqItem5,rewardItem1,rewardItem2,rewardItem3,rewardItem4 FROM LOTTERY_EVENT_SETTINGS')
ids = [int(x) for line in rows.splitlines() for x in line.split('|') if x.strip().isdigit()]
K.item_icons(ids, os.path.join(HERE, 'ev_ui'))
print('lottery skin ->', OUT)
