r"""HopeGuard ACS start splash skin (hopeguard_banner.cpp), only from the game's own UI pieces:
  - frame: the green message box (ui\re_message_box.dxt, kopanel.green_frame)
  - bar:   Progress_Loading of the game's loading screen re_loadingscreen2022.uif (ui\ui_loding.dxt): empty + full
Output: hg_ui\banner.pus, bar_empty.pus, bar_full.pus + hg_layout.h"""
import os, ntpath
from PIL import Image
import kopanel as K
import uif3

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, 'hg_ui')

def img_of(e):
    T = K.tex(ntpath.basename(e['tex'])); W_, H_ = T.size; u0, v0, u1, v1 = e['uv']; l, t, r, b = e['rect']
    return T.crop((round(u0 * W_), round(v0 * H_), round(u1 * W_), round(v1 * H_))).resize((r - l, b - t), Image.LANCZOS)

load, _, _ = uif3.load(os.path.join(HERE, 'native_ui', 're_loadingscreen2022.uif'))
prog = next(e for e in load['children'] if e.get('id') == 'Progress_Loading')
empty, full = [img_of(k) for k in prog['children'] if k['type'] == 'IMAGE'][:2]
bw, bh = empty.size                                   # 304 x 20

W, FH = 380, 112                                      # banner frame
GAP = 6
H = FH + GAP + bh
os.makedirs(OUT, exist_ok=True)
K.save_pus(K.green_frame(W, FH), os.path.join(OUT, 'banner.pus'))
K.save_pus(empty, os.path.join(OUT, 'bar_empty.pus'))
K.save_pus(full, os.path.join(OUT, 'bar_full.pus'))
bx, by = (W - bw) // 2, FH + GAP

prev = Image.new('RGBA', (W, H), (0, 0, 0, 255))
prev.alpha_composite(Image.open(os.path.join(OUT, 'banner.png')), (0, 0))
prev.alpha_composite(empty, (bx, by))
prev.alpha_composite(full.crop((0, 0, bw * 6 // 10, bh)), (bx, by))
prev.save(os.path.join(OUT, '_preview.png'))
with open(os.path.join(HERE, 'hg_layout.h'), 'w') as f:
    f.write('// Generated by build_hopeguard_banner.py -- do not edit by hand.\n#pragma once\n')
    f.write('static const int HG_W = %d, HG_H = %d, HG_FRAME_H = %d;\n' % (W, H, FH))
    f.write('static const int HG_TITLE[4] = { 20, 22, %d, 52 };\n' % (W - 20))
    f.write('static const int HG_TEXT[4] = { 20, 54, %d, 86 };\n' % (W - 20))
    f.write('static const int HG_BAR[4] = { %d, %d, %d, %d };\n' % (bx, by, bx + bw, by + bh))
print('splash ->', OUT, W, H)
