r"""Drop button next to the target bar (drop_button.cpp): the target bar's own small "Board" button
(re_target_framebar.uif Button_Board, ui\re_mini_hp_bar.dxt): its frame + the normal / over / down faces.
Output: dropbtn_ui\btn_n.pus, btn_o.pus, btn_d.pus + dropbtn_layout.h"""
import os, ntpath
from PIL import Image
import kopanel as K
import uif3

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, 'dropbtn_ui')
root, _, _ = uif3.load(os.path.join(HERE, 'native_ui', 're_target_framebar.uif'))
btn = next(e for e in root['children'] if e.get('id') == 'Button_Board')
imgs = [k for k in btn['children'] if k['type'] == 'IMAGE']

def img_of(e):
    T = K.tex(ntpath.basename(e['tex'])); W_, H_ = T.size; u0, v0, u1, v1 = e['uv']; l, t, r, b = e['rect']
    return T.crop((round(u0 * W_), round(v0 * H_), round(u1 * W_), round(v1 * H_))).resize((r - l, b - t), Image.LANCZOS)

frame = imgs[0]; fl, ft, fr, fb = frame['rect']
W, H = fr - fl, fb - ft
os.makedirs(OUT, exist_ok=True)
faces = imgs[1:4]                                        # button states as the uif lists them: normal, down, over
for name, face in (('btn_n', faces[0]), ('btn_d', faces[1]), ('btn_o', faces[2])):
    im = Image.new('RGBA', (W, H), (0, 0, 0, 0))
    im.alpha_composite(img_of(frame), (0, 0))
    l, t, r, b = face['rect']
    im.alpha_composite(img_of(face), (l - fl, t - ft))
    K.save_pus(im, os.path.join(OUT, name + '.pus'))
bl, bt, br, bb = faces[0]['rect']
prev = Image.new('RGBA', (W * 3 + 8, H), (30, 30, 30, 255))
for i, n in enumerate(('btn_n', 'btn_o', 'btn_d')):
    prev.alpha_composite(Image.open(os.path.join(OUT, n + '.png')), (i * (W + 4), 0))
prev.resize((prev.width * 3, prev.height * 3), Image.NEAREST).save(os.path.join(OUT, '_preview.png'))
with open(os.path.join(HERE, 'dropbtn_layout.h'), 'w') as f:
    f.write('// Generated by build_dropbtn_assets.py -- do not edit by hand.\n#pragma once\n')
    f.write('static const int DB_W = %d, DB_H = %d;\n' % (W, H))
    f.write('static const int DB_FACE[4] = { %d, %d, %d, %d };\n' % (bl - fl, bt - ft, br - fl, bb - ft))
print('drop button ->', OUT, W, H)
