"""Job Change window skin (jobchange_panel.cpp) = the old HSACSX class selection window jobchangedm.uif as is
(4 class cards, a button under each, close button), scaled to fit a 1024 wide game window. The captions are drawn
by the panel itself (the uif's own say "Death Match Event").
uif reader + texture loader: the head of build_gm_assets.py.
Output: jc_ui\\*.pus (client: HopeGuard\\jc_ui) + jc_layout.h
Usage: python build_jobchange_assets.py [uif] [textureDir]"""
import os, sys
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
_argv = sys.argv; sys.argv = sys.argv[:1]
exec(open(os.path.join(HERE, 'build_gm_assets.py'), encoding='utf-8').read().split('# ------------------------------------------------------------------ relabels')[0])
sys.argv = _argv
UIF = sys.argv[1] if len(sys.argv) > 1 else r'D:\25X VE 26X ESKİLER\25xxacs_2\Tools\UifWork\jobchangedm.uif'
TEXDIRS = [sys.argv[2] if len(sys.argv) > 2 else r'D:\25X VE 26X ESKİLER\25xxacs_2\Release\HSACSX\UI']
OUT = os.path.join(HERE, 'jc_ui')
os.makedirs(OUT, exist_ok=True)
SCALE = 0.8

_load = load_tex
def load_tex(name):                                    # the class art is kept as jobchange.dxt.off in that folder
    try: return _load(name)
    except FileNotFoundError: return _load(name + '.off')

root = read_uif(UIF)
images = [e for e in root if e['type'] == 'IMAGE' and e.get('tex')]
strings = [e for e in root if e['type'] == 'STRING']
buttons = {e['id']: e for e in root if e['type'] == 'BUTTON'}
X0 = min(i['rect'][0] for i in images); Y0 = min(i['rect'][1] for i in images)
W = max(i['rect'][2] for i in images) - X0; H = max(i['rect'][3] for i in images) - Y0
def sc(rect): return [round((rect[0] - X0) * SCALE), round((rect[1] - Y0) * SCALE), round((rect[2] - X0) * SCALE), round((rect[3] - Y0) * SCALE)]
def scaled(img): return img.resize((max(1, round(img.size[0] * SCALE)), max(1, round(img.size[1] * SCALE))), Image.LANCZOS)

bg = Image.new('RGBA', (W, H), (0, 0, 0, 0))
for i in images: bg.alpha_composite(piece(i), (i['rect'][0] - X0, i['rect'][1] - Y0))
bg = scaled(bg); save_pus(bg, 'bg')

# button states: Reserved 0..3 = normal / down / on / disable
def states(b): return {k['res']: k for k in b['children'] if k['type'] == 'IMAGE' and k.get('tex')}
st = states(buttons['btn_warrior'])
for n, key in (('btn_n', 0), ('btn_d', 1), ('btn_o', 2)): save_pus(scaled(piece(st.get(key, st[0]))), n)
st = states(buttons['btn_close'])
for n, key in (('close_n', 0), ('close_d', 1), ('close_o', 2)): save_pus(scaled(piece(st.get(key, st[0]))), n)

# cards left to right = Warrior, Rogue, Mage, Priest (the order of the uif's captions and of the class art)
heads = sorted([s for s in strings if s['text'].startswith('Ready Class')], key=lambda s: s['rect'][0])
btns = sorted([b for k, b in buttons.items() if k != 'btn_close'], key=lambda b: b['rect'][0])
plates = sorted([i for i in images if i['tex'].lower().endswith('cyber_character3.dxt')], key=lambda i: i['rect'][0])
title = next(s for s in strings if 'Match' in s['text'])
text = next(s for s in strings if s['text'].startswith('Select the class'))

L = ['// Generated by build_jobchange_assets.py from jobchangedm.uif -- do not edit by hand.', '#pragma once',
     'static const int JC_W = %d, JC_H = %d;' % bg.size]
def one(name, rect): L.append('static const int JC_%s[4] = { %d, %d, %d, %d };' % ((name,) + tuple(sc(rect))))
def four(name, items): L.append('static const int JC_%s[4][4] = { %s };' % (name, ', '.join('{ %d, %d, %d, %d }' % tuple(sc(i['rect'])) for i in items)))
one('TITLE', title['rect']); one('TEXT', text['rect']); one('CLOSE', buttons['btn_close']['rect'])
four('CARD', plates); four('HEAD', heads); four('BTN', btns)
L.append('static const int JC_STATUS[4] = { 44, %d, %d, %d };' % (bg.size[1] - 43, bg.size[0] - 44, bg.size[1] - 19))   # the strip under the cards
open(os.path.join(HERE, 'jc_layout.h'), 'w', newline='\r\n').write('\n'.join(L) + '\n')

prev = Image.new('RGBA', bg.size, (40, 40, 40, 255)); prev.alpha_composite(bg)
bn = scaled(piece(states(buttons['btn_warrior'])[0]))
for b in btns: prev.alpha_composite(bn, tuple(sc(b['rect'])[:2]))
prev.save(os.path.join(OUT, '_preview.png'))
print('job change skin %dx%d ->' % bg.size, OUT)
