r"""Tag Change window skin (tag_panel.cpp), made only from the game's own UI pieces:
  - frame:   the green message box (ui\re_message_box.dxt, kopanel.green_frame)
  - edit:    the clan-name edit field of re_creat_clan.uif (ui\re_message_box.dxt)
  - palette: the chat colour palette Img_palet of re_chatcolor.uif (ui\plate2.dxt), clicked to pick a colour
  - buttons: btn_ok of re_msgboxokcancel.uif with the painted caption cut out (as build_reconnect_assets.py)
Output: tag_ui\*.pus + tag_layout.h
"""
import os, ntpath
from PIL import Image
import kopanel as K
import uif3

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, 'tag_ui')

def img_of(e, size=None):
    T = K.tex(ntpath.basename(e['tex'])); W_, H_ = T.size; u0, v0, u1, v1 = e['uv']; l, t, r, b = e['rect']
    return T.crop((round(u0 * W_), round(v0 * H_), round(u1 * W_), round(v1 * H_))).resize(size or (r - l, b - t), Image.LANCZOS)

# the pieces, straight from the game's uif files (native_ui\ keeps copies taken from UI\ui.src)
msg, _, _ = uif3.load(os.path.join(HERE, 'native_ui', 're_msgboxokcancel.uif'))
clan, _, _ = uif3.load(os.path.join(HERE, 'native_ui', 're_creat_clan.uif'))
chat, _, _ = uif3.load(os.path.join(HERE, 'native_ui', 're_chatcolor.uif'))
btn_ok = next(e for e in msg['children'] if e.get('id') == 'btn_ok')
edit = next(e for e in clan['children'] if e.get('id') == 'Edit_Clan')
palet = next(e for e in chat['children'] if e.get('id') == 'Img_palet')

W, H = 356, 330
L = {}
def r(name, x0, y0, x1, y1): L[name] = (x0, y0, x1, y1)
pw, ph = palet['rect'][2] - palet['rect'][0], palet['rect'][3] - palet['rect'][1]     # 235 x 130, kept 1:1
bw, bh = btn_ok['rect'][2] - btn_ok['rect'][0], btn_ok['rect'][3] - btn_ok['rect'][1]   # 107 x 36
r('title', 20, 16, W - 20, 40)
r('text', 26, 40, W - 26, 58)
r('edit', 60, 62, W - 60, 87)
r('palette', (W - pw) // 2, 94, (W - pw) // 2 + pw, 94 + ph)
r('preview', 26, 228, W - 26, 248)
r('status', 26, 248, W - 26, 266)
r('btn_ok', 46, 274, 46 + bw, 274 + bh)
r('btn_cancel', W - 46 - bw, 274, W - 46, 274 + bh)

bg = K.green_frame(W, H)
ex0, ey0, ex1, ey1 = L['edit']
e_img = img_of(edit['children'][0])
bg.alpha_composite(K.slice3(e_img, ex1 - ex0, ey1 - ey0, 8), (ex0, ey0))
os.makedirs(OUT, exist_ok=True)
K.save_pus(bg, os.path.join(OUT, 'bg.pus'))
K.save_pus(img_of(palet, (pw, ph)), os.path.join(OUT, 'palette.pus'))
imgs = [img_of(k) for k in btn_ok['children'] if k['type'] == 'IMAGE']
iw, ih = imgs[0].size
for st, im in (('n', imgs[0]), ('d', imgs[1]), ('o', imgs[2])):
    K.save_pus(K.slice3(im, bw, bh, 10, mid=(12, 22)), os.path.join(OUT, 'btn_%s.pus' % st))

prev = bg.copy()
prev.alpha_composite(Image.open(os.path.join(OUT, 'palette.png')), L['palette'][:2])
for k in ('btn_ok', 'btn_cancel'):
    prev.alpha_composite(Image.open(os.path.join(OUT, 'btn_n.png')), L[k][:2])
prev.save(os.path.join(OUT, '_preview.png'))
with open(os.path.join(HERE, 'tag_layout.h'), 'w') as f:
    f.write('// Generated by build_tag_assets.py -- do not edit by hand.\n#pragma once\n')
    f.write('static const int TG_W = %d, TG_H = %d;\n' % (W, H))
    for k, v in L.items():
        f.write('static const int TG_%s[4] = { %d, %d, %d, %d };\n' % ((k.upper(),) + tuple(v)))
print('tag skin ->', OUT)
