r"""Drop box panel skin (dropbox_panel.cpp), the same as the reference F:\resimlers\resimlers\deneme1.png: a small
teal header with a button (take all) and gold framed item cells under it, on the right side of the screen.
Pieces of the game's atlas ui\tournament_chaos_2021_a01.dxt (same set as the lottery / event panels).
Output: dropbox_ui\*.pus + dropbox_layout.h
"""
import os
from PIL import Image
import kopanel as K

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, 'dropbox_ui')
T = K.tex('tournament_chaos_2021_a01.dxt')
GOLDFRAME = K.piece(T, (4, 26, 96, 120))
TEAL = K.piece(T, (4, 707, 196, 777))
BTN = [K.piece(T, (352, 243, 386, 272)), K.piece(T, (352, 272, 386, 302)), K.piece(T, (352, 302, 386, 335))]

CELL, HEAD_H, W = 46, 20, 50
os.makedirs(OUT, exist_ok=True)
cell = Image.new('RGBA', (CELL, CELL), (0, 0, 0, 0))
cell.alpha_composite(Image.new('RGBA', (CELL - 8, CELL - 8), (34, 26, 18, 235)), (4, 4))
cell.alpha_composite(K.slice9(GOLDFRAME, CELL, CELL, 10), (0, 0))
K.save_pus(cell, os.path.join(OUT, 'cell.pus'))
head = K.slice3(TEAL, W, HEAD_H, 8)
K.save_pus(head, os.path.join(OUT, 'head.pus'))
for st, img in zip(('n', 'o', 'd'), BTN):
    K.save_pus(K.fit(img, 14, 14), os.path.join(OUT, 'take_%s.pus' % st))

prev = Image.new('RGBA', (W, HEAD_H + 4 * (CELL + 2)), (60, 50, 30, 255))
prev.alpha_composite(head, (0, 0)); prev.alpha_composite(Image.open(os.path.join(OUT, 'take_n.png')), (W - 17, 3))
for i in range(4):
    prev.alpha_composite(cell, (2, HEAD_H + 2 + i * (CELL + 2)))
prev.save(os.path.join(OUT, '_preview.png'))
with open(os.path.join(HERE, 'dropbox_layout.h'), 'w') as f:
    f.write('// Generated by build_dropbox_assets.py -- do not edit by hand.\n#pragma once\n')
    f.write('static const int DB_W = %d, DB_CELL = %d, DB_HEAD_H = %d, DB_TAKE[4] = { %d, 3, %d, 17 };\n' % (W, CELL, HEAD_H, W - 17, W - 3))
print('drop box skin ->', OUT)
