r"""Solo Cape top-bar icon (solocape_icon.cpp), from the game's own art:
  - the round gold coin of the coin gauge (re_eventcoinstate.uif, ui\coin shop_a01.dxt): image "13" plain,
    image "12" (with sparkles) for the hover state
  - the Solo Cape item icon (ITEM 810522000 -> itemicon_*.dxt), cut to a circle inside the coin's rim
Output: solocape_ui\icon_n.pus, icon_o.pus + solocape_layout.h"""
import os
from PIL import Image, ImageDraw
import kopanel as K
import uif3

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, 'solocape_ui')
SIZE = 53

root, _, _ = uif3.load(os.path.join(HERE, 'native_ui', 're_eventcoinstate.uif'))
T = K.tex('coin shop_a01.dxt'); W, H = T.size
imgs = []
def walk(e):
    if e['type'] == 'IMAGE':
        u0, v0, u1, v1 = e['uv']; imgs.append(T.crop((round(u0 * W), round(v0 * H), round(u1 * W), round(v1 * H))).resize((SIZE, SIZE), Image.LANCZOS))
    for k in e.get('children', []): walk(k)
walk(root)
coin_plain, coin_glow = imgs[13], imgs[12]

icon_id = int(K.sql("SELECT ItemIconID1 FROM ITEM WHERE Num=810522000").strip())
icon = K.load_tex(K._icon_file(icon_id)).convert('RGBA')
icon = icon.crop((0, 0, 45, 45)) if icon.size[0] >= 45 else icon
bb = coin_plain.getchannel('A').point(lambda a: 255 if a > 128 else 0).getbbox()   # the coin inside the 53x53 cell
CX, CY = (bb[0] + bb[2]) / 2.0, (bb[1] + bb[3]) / 2.0
R = int(min(bb[2] - bb[0], bb[3] - bb[1]) / 2) - 3        # inside the coin's rim
icon = icon.resize((2 * R, 2 * R), Image.LANCZOS)
mask = Image.new('L', (2 * R, 2 * R), 0)
ImageDraw.Draw(mask).ellipse((0, 0, 2 * R - 1, 2 * R - 1), fill=255)
disc = Image.new('RGBA', (2 * R, 2 * R), (0, 0, 0, 0)); disc.paste(icon, (0, 0), mask)

os.makedirs(OUT, exist_ok=True)
for name, base in (('icon_n', coin_plain), ('icon_o', coin_glow)):
    im = base.copy()
    im.alpha_composite(disc, (int(round(CX - R)), int(round(CY - R))))
    K.save_pus(im, os.path.join(OUT, name + '.pus'))
prev = Image.new('RGBA', (SIZE * 2 + 12, SIZE + 8), (30, 30, 30, 255))
prev.alpha_composite(Image.open(os.path.join(OUT, 'icon_n.png')), (4, 4))
prev.alpha_composite(Image.open(os.path.join(OUT, 'icon_o.png')), (SIZE + 8, 4))
prev.resize((prev.width * 3, prev.height * 3), Image.NEAREST).save(os.path.join(OUT, '_preview.png'))
with open(os.path.join(HERE, 'solocape_layout.h'), 'w') as f:
    f.write('// Generated by build_solocape_icon.py -- do not edit by hand.\n#pragma once\n')
    f.write('static const int SCI_SIZE = %d;\n' % SIZE)
print('solo cape icon ->', OUT, 'item icon', icon_id, 'coin box', bb, 'R', R)
