r"""Item tooltip skin (item_tooltip.cpp), the pieces of the game's own inventory tooltip re_newtooltip.uif:
  - background img_back  (ui\ui_message.dxt)   -> itemtip_ui\back.pus (stretched in code)
  - separator  img_bar_0 (ui\co_pat_ui_02.dxt)  -> itemtip_ui\bar.pus
  - durability progress pro_Durabillity (ui\re_main_ui_02.dxt) -> itemtip_ui\dur_bg.pus, dur_fill.pus
Output: itemtip_ui\*.pus + itemtip_layout.h (the uif's positions)"""
import os, ntpath
from PIL import Image
import kopanel as K
import uif3

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, 'itemtip_ui')
root, _, _ = uif3.load(os.path.join(HERE, 'native_ui', 're_newtooltip.uif'))

def find(e, id_):
    for c in e.get('children', []):
        if c.get('id') == id_: return c
        f = find(c, id_)
        if f: return f
    return None

def crop(e):
    T = K.tex(ntpath.basename(e['tex'])); W_, H_ = T.size; u0, v0, u1, v1 = e['uv']
    return T.crop((round(u0 * W_), round(v0 * H_), round(u1 * W_), round(v1 * H_)))

os.makedirs(OUT, exist_ok=True)
K.save_pus(crop(find(root, 'img_back')), os.path.join(OUT, 'back.pus'))
bar = find(root, 'img_bar_0'); l, t, r, b = bar['rect']
K.save_pus(crop(bar).resize((r - l, b - t), Image.LANCZOS), os.path.join(OUT, 'bar.pus'))
dur = find(root, 'pro_Durabillity')
pims = [c for c in dur['children'] if c['type'] == 'IMAGE']
dl, dt, dr, db = dur['rect']
K.save_pus(crop(pims[0]).resize((dr - dl, db - dt), Image.LANCZOS), os.path.join(OUT, 'dur_bg.pus'))
K.save_pus(crop(pims[1]).resize((dr - dl, db - dt), Image.LANCZOS), os.path.join(OUT, 'dur_fill.pus'))

def rect(id_): return find(root, id_)['rect']
with open(os.path.join(HERE, 'itemtip_layout.h'), 'w') as f:
    f.write('// Generated by build_itemtip_assets.py -- do not edit by hand (re_newtooltip.uif positions).\n#pragma once\n')
    f.write('static const int IT_W = %d;\n' % (find(root, 'img_back')['rect'][2] - find(root, 'img_back')['rect'][0]))
    for k, id_ in (('EQUIP', 'str_equip'), ('ICON', 'img_icon'), ('NAME', 'str_Name'), ('GRADE', 'str_Grade'), ('TYPE', 'str_type'),
                   ('DURTXT', 'str_Durabillity'), ('DURBAR', 'pro_Durabillity'), ('BAR0', 'img_bar_0'), ('BAR1', 'img_bar_1'), ('LINE0', 'string_0')):
        f.write('static const int IT_%s[4] = { %d, %d, %d, %d };\n' % ((k,) + tuple(rect(id_))))
prev = Image.new('RGBA', (300, 200), (60, 60, 60, 255))
prev.alpha_composite(Image.open(os.path.join(OUT, 'back.png')).resize((298, 190)), (0, 0))
prev.alpha_composite(Image.open(os.path.join(OUT, 'bar.png')), (4, 20))
prev.alpha_composite(Image.open(os.path.join(OUT, 'dur_bg.png')), (236, 108))
prev.save(os.path.join(OUT, '_preview.png'))
print('item tooltip ->', OUT)
