// Generated by build_cind_assets.py from 2585 re_funclass.hsacsx -- do not edit by hand.
#pragma once
static const int CIS_W = 659, CIS_H = 361;
static const int CIS_TAB_W = 119, CIS_TAB_H = 32;
struct CisSprite { const char* name; int l, t, r, b; };
static const CisSprite CIS_SPRITES[] = {
    { "frame", 0, 0, 659, 361 },
    { "emb_karus", 71, 11, 97, 37 },
    { "emb_elmo", 561, 11, 587, 37 },
    { "btn_warrior_n", 27, 60, 167, 289 },
    { "btn_warrior_d", 27, 60, 167, 289 },
    { "btn_warrior_o", 27, 60, 167, 289 },
    { "btn_rogue_n", 182, 60, 322, 289 },
    { "btn_rogue_d", 182, 60, 322, 289 },
    { "btn_rogue_o", 182, 60, 322, 289 },
    { "btn_mage_n", 337, 60, 477, 289 },
    { "btn_mage_d", 337, 60, 477, 289 },
    { "btn_mage_o", 337, 60, 477, 289 },
    { "btn_priest_n", 492, 60, 632, 289 },
    { "btn_priest_d", 492, 60, 632, 289 },
    { "btn_priest_o", 492, 60, 632, 289 },
    { "btn_close_n", 626, 32, 660, 66 },
    { "btn_close_d", 626, 32, 660, 66 },
    { "btn_close_o", 626, 32, 660, 66 },
    { "tab_n", 0, 0, 119, 32 },
    { "tab_d", 0, 0, 119, 32 },
    { "tab_o", 0, 0, 119, 32 },
};
static const int CIS_BTN_WARRIOR[4] = { 27, 60, 167, 289 };
static const int CIS_BTN_ROGUE[4] = { 182, 60, 322, 289 };
static const int CIS_BTN_MAGE[4] = { 337, 60, 477, 289 };
static const int CIS_BTN_PRIEST[4] = { 492, 60, 632, 289 };
static const int CIS_BTN_CLOSE[4] = { 626, 32, 660, 66 };
static const int CIS_TXT_KARUS_KILL_COUNT[4] = { 108, 10, 208, 39 };  // "1000" color FFFFFFFF h16
static const int CIS_TXT_ELMO_KILL_COUNT[4] = { 450, 10, 550, 39 };  // "1000" color FFFFFFFF h16
static const int CIS_TXT_YOUR_KILL_COUNT[4] = { 160, 308, 273, 338 };  // "1000" color FFFFFFFF h16
static const int CIS_TXT_YOUR_DEATH_COUNT[4] = { 382, 308, 495, 338 };  // "1000" color FFFFFFFF h16
static const int CIS_LABEL_0[4] = { 69, 9, 589, 22 };  // "FUN CLASS EVENT" color FFFFFF80 h10
static const int CIS_LABEL_1[4] = { 496, 308, 589, 337 };  // ":  Count Of Death  " color FFFFFF80 h10
static const int CIS_LABEL_2[4] = { 66, 308, 159, 337 };  // "Your Kill Count  :" color FFFFFF80 h10
static const int CIS_LABEL_3[4] = { 65, 310, 591, 323 };  // "Remaining Time : " color FFFFFF80 h10
static const int CIS_TXT_REMAINING_TIME[4] = { 63, 324, 590, 340 };  // "00:00:00" color FFFFFFFF h16
static const int CIS_TXT_SELECT_TIME[4] = { 37, 24, 622, 42 };  // "00:00:00" color FFFFFF00 h10
