// Generated by build_cr_assets.py from re_collection_race.uif -- do not edit by hand.
#pragma once
static const int CRS_W = 241, CRS_H = 446;
struct CrsSprite { const char* name; int l, t, r, b; };
static const CrsSprite CRS_SPRITES[] = {
    { "head", 3, 9, 222, 56 },
    { "time", 10, 54, 216, 103 },
    { "rewhead", 10, 269, 216, 298 },
    { "tgt0", 10, 102, 216, 161 },
    { "rew0", 10, 297, 216, 346 },
    { "tgt1", 10, 158, 216, 216 },
    { "rew1", 10, 343, 216, 391 },
    { "tgt2", 10, 210, 216, 269 },
    { "rew2", 10, 389, 216, 437 },
    { "btn_min_n", 164, 20, 191, 43 },
    { "btn_min_d", 164, 20, 191, 43 },
    { "btn_min_o", 164, 20, 191, 43 },
    { "btn_max_n", 164, 20, 191, 43 },
    { "btn_max_d", 164, 20, 191, 43 },
    { "btn_max_o", 164, 20, 191, 43 },
    { "btn_close_n", 190, 17, 217, 44 },
    { "btn_close_d", 190, 17, 217, 44 },
    { "btn_close_o", 190, 17, 217, 44 },
};
static const int CRS_BTN_CLOSE[4] = { 190, 17, 217, 44 };
static const int CRS_BTN_MIN[4] = { 164, 20, 191, 43 };
static const int CRS_ICON_0[4] = { 19, 108, 61, 150 };
static const int CRS_ICON_1[4] = { 19, 164, 61, 206 };
static const int CRS_ICON_2[4] = { 19, 219, 61, 261 };
static const int CRS_RICON_0[4] = { 17, 305, 55, 339 };
static const int CRS_RICON_1[4] = { 17, 351, 55, 385 };
static const int CRS_RICON_2[4] = { 18, 398, 55, 431 };
static const int CRS_RTXT_RATE_0[4] = { 86, 323, 208, 339 };  // color FFFFFFFF h9 Arial
static const int CRS_RTXT_RATE_1[4] = { 86, 369, 208, 385 };  // color FFFFFFFF h9 Arial
static const int CRS_RTXT_RATE_2[4] = { 86, 415, 208, 431 };  // color FFFFFFFF h9 Arial
static const int CRS_RTXT_RETURN_FIRST_0[4] = { 62, 304, 209, 320 };  // color FFFFFFFF h9 Arial
static const int CRS_RTXT_RETURN_FIRST_1[4] = { 62, 350, 209, 366 };  // color FFFFFFFF h9 Arial
static const int CRS_RTXT_RETURN_FIRST_2[4] = { 62, 396, 209, 412 };  // color FFFFFFFF h9 Arial
static const int CRS_RTXT_RETURN_SECOND_0[4] = { 68, 323, 82, 339 };  // color FFFFFFFF h9 Arial
static const int CRS_RTXT_RETURN_SECOND_1[4] = { 68, 369, 82, 385 };  // color FFFFFFFF h9 Arial
static const int CRS_RTXT_RETURN_SECOND_2[4] = { 68, 415, 82, 431 };  // color FFFFFFFF h9 Arial
static const int CRS_TEXT_EVENT_NAME[4] = { 13, 22, 166, 39 };  // color FFFFFF00 h10 Verdana
static const int CRS_TEXT_HEADER[4] = { 16, 273, 210, 292 };  // color FFFFFF80 h10 Verdana
static const int CRS_TEXT_TIME[4] = { 118, 76, 183, 93 };  // color FFFFFFFF h10 Verdana
static const int CRS_TEXT_TIME_LABEL[4] = { 65, 76, 109, 93 };  // color FFFFFFFF h10 Verdana
static const int CRS_TEXT_WINNERS[4] = { 118, 55, 183, 72 };  // color FF00FFFF h10 Verdana
static const int CRS_TEXT_WINNERS_LABEL[4] = { 65, 55, 112, 72 };  // color FF00FFFF h10 Verdana
static const int CRS_TXT_NEEDS_FIRST_0[4] = { 69, 109, 209, 126 };  // color FFFFFFFF h9 Verdana
static const int CRS_TXT_NEEDS_FIRST_1[4] = { 69, 165, 209, 181 };  // color FFFFFFFF h9 Verdana
static const int CRS_TXT_NEEDS_FIRST_2[4] = { 69, 220, 209, 237 };  // color FFFFFFFF h9 Verdana
static const int CRS_TXT_NEEDS_SECOND_0[4] = { 69, 131, 209, 147 };  // color FFFFFFFF h9 Verdana
static const int CRS_TXT_NEEDS_SECOND_1[4] = { 69, 187, 209, 204 };  // color FFFFFFFF h9 Verdana
static const int CRS_TXT_NEEDS_SECOND_2[4] = { 69, 242, 209, 259 };  // color FFFFFFFF h9 Verdana
