// Generated by build_cross_assets.py (Cross Exchange skin, HSACSX re_piecechange) -- do not edit by hand.
#pragma once
#ifndef RCE_TYPES
#define RCE_TYPES
struct RceRect { int l, t, r, b; };
struct RceSprite { const char* name; RceRect rc; };
#endif
static const int RCE_W = 430, RCE_H = 602;
static const int RCE_SLOT_COUNT = 25;
static const RceSprite RCE_SPRITES[] = {
    { "bg", { 0, 0, 430, 602 } },
    { "coupon", { 46, 251, 89, 294 } },
    { "exchange_n", { 150, 289, 296, 305 } },
    { "exchange_d", { 150, 289, 296, 305 } },
    { "exchange_o", { 150, 289, 296, 305 } },
    { "close_n", { 378, 7, 412, 40 } },
    { "close_d", { 378, 7, 412, 40 } },
    { "close_o", { 378, 7, 412, 40 } },
};
static const RceRect RCE_COUPON = { 48, 253, 87, 292 };
static const RceRect RCE_TITLE = { 110, 20, 316, 50 };
static const RceRect RCE_BTN_EXCHANGE = { 150, 289, 296, 305 };
static const RceRect RCE_BTN_CLOSE = { 378, 7, 412, 40 };
static const RceRect RCE_SLOTS[25] = {
    { 69, 70, 108, 106 },
    { 118, 70, 157, 106 },
    { 167, 70, 206, 106 },
    { 216, 70, 255, 106 },
    { 265, 70, 304, 106 },
    { 314, 70, 353, 106 },
    { 69, 113, 108, 149 },
    { 118, 113, 157, 149 },
    { 167, 113, 206, 149 },
    { 216, 113, 255, 149 },
    { 265, 113, 304, 149 },
    { 314, 113, 353, 149 },
    { 69, 156, 108, 192 },
    { 118, 156, 157, 192 },
    { 167, 156, 206, 192 },
    { 216, 156, 255, 192 },
    { 265, 156, 304, 192 },
    { 314, 156, 353, 192 },
    { 69, 199, 108, 235 },
    { 118, 199, 157, 235 },
    { 167, 199, 206, 235 },
    { 216, 199, 255, 235 },
    { 265, 199, 304, 235 },
    { 314, 199, 353, 235 },
    { 335, 253, 374, 292 }
};
static const RceRect RCE_INV[28] = {
    { 39, 327, 82, 370 },
    { 89, 327, 132, 370 },
    { 139, 327, 182, 370 },
    { 189, 327, 232, 370 },
    { 239, 327, 282, 370 },
    { 289, 327, 332, 370 },
    { 339, 327, 382, 370 },
    { 39, 377, 82, 420 },
    { 89, 377, 132, 420 },
    { 139, 377, 182, 420 },
    { 189, 377, 232, 420 },
    { 239, 377, 282, 420 },
    { 289, 377, 332, 420 },
    { 339, 377, 382, 420 },
    { 39, 427, 82, 470 },
    { 89, 427, 132, 470 },
    { 139, 427, 182, 470 },
    { 189, 427, 232, 470 },
    { 239, 427, 282, 470 },
    { 289, 427, 332, 470 },
    { 339, 427, 382, 470 },
    { 39, 478, 82, 521 },
    { 89, 478, 132, 521 },
    { 139, 478, 182, 521 },
    { 189, 478, 232, 521 },
    { 239, 478, 282, 521 },
    { 289, 478, 332, 521 },
    { 339, 478, 382, 521 }
};
static const RceRect RCE_KC_LABEL = { 100, 251, 124, 267 };
static const RceRect RCE_KC = { 126, 251, 204, 267 };
static const RceRect RCE_TL_LABEL = { 214, 251, 236, 267 };
static const RceRect RCE_TL = { 238, 251, 316, 267 };
static const RceRect RCE_GOLD = { 148, 271, 298, 287 };
static const RceRect RCE_RESULT = { 333, 251, 376, 294 };
static const RceRect RCE_WEIGHT = { 36, 547, 236, 567 };
static const RceRect RCE_NOAH = { 272, 546, 372, 566 };
