// Generated by build_csw_assets.py from re_siege_warfare_challenge.uif -- do not edit by hand.
#pragma once
static const int CWS_W = 684, CWS_H = 692, CWS_ROWS = 20, CWS_ROW_PITCH = 25;
static const int CWS_CLOSE[4] = { 643, 2, 677, 35 };
static const int CWS_FOOT_LABEL[4] = { 358, 628, 527, 653 };
static const int CWS_FOOT_VALUE[4] = { 531, 634, 618, 649 };
static const int CWS_H_CLAN[4] = { 259, 90, 402, 115 };
static const int CWS_H_DEATH[4] = { 534, 91, 654, 116 };
static const int CWS_H_ICON[4] = { 114, 90, 171, 115 };
static const int CWS_H_KILL[4] = { 497, 91, 547, 116 };
static const int CWS_H_RANK[4] = { 55, 91, 120, 116 };
static const int CWS_ROW_DEATH[4] = { 565, 120, 613, 140 };
static const int CWS_ROW_KILL[4] = { 499, 120, 547, 140 };
static const int CWS_ROW_MARK[4] = { 132, 119, 152, 139 };
static const int CWS_ROW_MYSELF_BG[4] = { 112, 118, 623, 140 };
static const int CWS_ROW_NAME[4] = { 199, 120, 459, 140 };
static const int CWS_ROW_RANK[4] = { 72, 120, 101, 140 };
static const int CWS_TITLE[4] = { 244, 21, 417, 46 };
