// Generated by build_dropmini_assets.py -- do not edit by hand.
#pragma once
static const int DB_CHEST = 30;
static const int DM_W = 346, DM_H = 284, DM_COLS = 6, DM_ROWS = 4, DM_PITCH = 51, DM_GX = 18, DM_GY = 46;
static const int DM_TITLE[4] = { 22, 14, 300, 40 };
static const int DM_CLOSE[4] = { 308, 12, 334, 38 };
static const int DM_INFO[4] = { 22, 256, 324, 272 };
