// Generated by build_evreward_assets.py -- do not edit by hand.
#pragma once
static const int ER_W = 248, ER_H = 492, ER_ROWS = 3;
static const int ER_TIME[4] = { 52, 20, 196, 46 };
static const int ER_CLOSE_X[4] = { 204, 21, 228, 45 };
static const int ER_TITLE[4] = { 12, 52, 230, 82 };
static const int ER_WIN_BAR[4] = { 12, 88, 230, 110 };
static const int ER_WIN_SLOT_0[4] = { 22, 114, 62, 154 };
static const int ER_WIN_NAME_0[4] = { 68, 115, 226, 134 };
static const int ER_WIN_COUNT_0[4] = { 110, 136, 184, 152 };
static const int ER_WIN_SLOT_1[4] = { 22, 158, 62, 198 };
static const int ER_WIN_NAME_1[4] = { 68, 159, 226, 178 };
static const int ER_WIN_COUNT_1[4] = { 110, 180, 184, 196 };
static const int ER_WIN_SLOT_2[4] = { 22, 202, 62, 242 };
static const int ER_WIN_NAME_2[4] = { 68, 203, 226, 222 };
static const int ER_WIN_COUNT_2[4] = { 110, 224, 184, 240 };
static const int ER_WIN_INFO[4] = { 12, 246, 230, 262 };
static const int ER_LOSE_BAR[4] = { 12, 266, 230, 288 };
static const int ER_LOSE_SLOT_0[4] = { 22, 292, 62, 332 };
static const int ER_LOSE_NAME_0[4] = { 68, 293, 226, 312 };
static const int ER_LOSE_COUNT_0[4] = { 110, 314, 184, 330 };
static const int ER_LOSE_SLOT_1[4] = { 22, 336, 62, 376 };
static const int ER_LOSE_NAME_1[4] = { 68, 337, 226, 356 };
static const int ER_LOSE_COUNT_1[4] = { 110, 358, 184, 374 };
static const int ER_LOSE_SLOT_2[4] = { 22, 380, 62, 420 };
static const int ER_LOSE_NAME_2[4] = { 68, 381, 226, 400 };
static const int ER_LOSE_COUNT_2[4] = { 110, 402, 184, 418 };
static const int ER_LOSE_INFO[4] = { 12, 424, 230, 440 };
static const int ER_CLOSE[4] = { 68, 446, 180, 472 };
