// Generated by build_hopeguard_banner.py -- do not edit by hand.
#pragma once
static const int HG_W = 380, HG_H = 138, HG_FRAME_H = 112;
static const int HG_TITLE[4] = { 20, 22, 360, 52 };
static const int HG_TEXT[4] = { 20, 54, 360, 86 };
static const int HG_BAR[4] = { 38, 118, 342, 138 };
