// Generated by build_itemtip_assets.py -- do not edit by hand (re_newtooltip.uif positions).
#pragma once
static const int IT_W = 298;
static const int IT_EQUIP[4] = { 17, 6, 286, 22 };
static const int IT_ICON[4] = { 8, 27, 53, 72 };
static const int IT_NAME[4] = { 55, 27, 285, 71 };
static const int IT_GRADE[4] = { 4, 70, 278, 86 };
static const int IT_TYPE[4] = { 4, 87, 275, 103 };
static const int IT_DURTXT[4] = { 4, 104, 218, 117 };
static const int IT_DURBAR[4] = { 236, 108, 281, 115 };
static const int IT_BAR0[4] = { 4, 20, 277, 28 };
static const int IT_BAR1[4] = { 4, 116, 277, 122 };
static const int IT_LINE0[4] = { 4, 124, 294, 148 };
