// Generated by build_jobchange_assets.py from jobchangedm.uif -- do not edit by hand.
#pragma once
static const int JC_W = 850, JC_H = 477;
static const int JC_TITLE[4] = { 334, 18, 510, 41 };
static const int JC_TEXT[4] = { 129, 111, 732, 134 };
static const int JC_CLOSE[4] = { 805, 9, 829, 33 };
static const int JC_CARD[4][4] = { { 58, 163, 227, 405 }, { 247, 163, 416, 405 }, { 434, 162, 603, 404 }, { 623, 163, 792, 405 } };
static const int JC_HEAD[4][4] = { { 62, 168, 218, 191 }, { 254, 169, 410, 192 }, { 442, 169, 598, 192 }, { 630, 169, 786, 192 } };
static const int JC_BTN[4][4] = { { 98, 198, 179, 217 }, { 294, 198, 374, 217 }, { 478, 198, 558, 218 }, { 669, 198, 750, 218 } };
static const int JC_STATUS[4] = { 44, 434, 806, 458 };
