// Generated by build_lottery_assets.py -- do not edit by hand.
#pragma once
static const int LT_W = 230, LT_H = 286, LT_TAB_W = 110, LT_TAB_H = 26;
static const int LT_TITLE[4] = { 40, 8, 190, 34 };
static const int LT_CLOSE[4] = { 198, 9, 222, 33 };
static const int LT_ROW_TIME[4] = { 12, 42, 218, 65 };
static const int LT_ROW_SOLD[4] = { 12, 67, 218, 90 };
static const int LT_ROW_TICKET[4] = { 12, 92, 218, 115 };
static const int LT_BUY_BOX[4] = { 12, 120, 218, 170 };
static const int LT_REQ_SLOT[4] = { 18, 125, 58, 165 };
static const int LT_REQ_FIELD[4] = { 62, 133, 162, 157 };
static const int LT_BUY[4] = { 166, 132, 212, 158 };
static const int LT_REWARDS_BAR[4] = { 12, 176, 218, 200 };
static const int LT_RANK_0[4] = { 16, 204, 64, 218 };
static const int LT_REWARD_0[4] = { 20, 220, 60, 260 };
static const int LT_RANK_1[4] = { 66, 204, 114, 218 };
static const int LT_REWARD_1[4] = { 70, 220, 110, 260 };
static const int LT_RANK_2[4] = { 116, 204, 164, 218 };
static const int LT_REWARD_2[4] = { 120, 220, 160, 260 };
static const int LT_RANK_3[4] = { 166, 204, 214, 218 };
static const int LT_REWARD_3[4] = { 170, 220, 210, 260 };
static const int LT_MSG[4] = { 12, 264, 218, 280 };
