// Generated by build_pus_assets.py from re_power_up_store.uif -- do not edit by hand.
#pragma once
struct PusRect { int l, t, r, b; };
static const int PUS_W = 807, PUS_H = 621;
static const int PUS_ICON = 45;
// card-relative rects (origin = card sprite top-left)
static const PusRect PUS_CARD_ICON = { 13, 28, 58, 70 };
static const PusRect PUS_CARD_NAME = { 9, 7, 156, 22 };
static const PusRect PUS_CARD_PRICE = { 88, 39, 156, 61 };
struct PusSlot { int cardX, cardY; PusRect buy; };
static const PusSlot PUS_SLOTS[12] = {
    { 40, 164, { 47, 248, 198, 274 } },
    { 228, 164, { 235, 248, 386, 274 } },
    { 415, 164, { 421, 248, 574, 274 } },
    { 592, 164, { 598, 248, 752, 274 } },
    { 41, 299, { 47, 383, 199, 409 } },
    { 228, 299, { 235, 383, 386, 409 } },
    { 415, 299, { 421, 383, 574, 409 } },
    { 592, 299, { 598, 383, 752, 409 } },
    { 41, 439, { 47, 523, 199, 549 } },
    { 228, 439, { 235, 523, 386, 549 } },
    { 415, 439, { 421, 523, 574, 549 } },
    { 592, 439, { 598, 523, 752, 549 } },
};
static const PusRect PUS_TABS[6] = { { 73, 113, 167, 139 }, { 183, 113, 277, 139 }, { 293, 113, 387, 139 }, { 402, 113, 496, 139 }, { 513, 113, 607, 139 }, { 623, 113, 717, 139 } };
static const PusRect PUS_CLOSE = { 756, 19, 782, 45 }, PUS_PREV = { 353, 572, 379, 598 }, PUS_NEXT = { 414, 572, 440, 598 };
static const PusRect PUS_TXT_CASH = { 69, 48, 146, 65 }, PUS_TXT_TL = { 197, 48, 273, 65 }, PUS_TXT_PAGE = { 373, 575, 421, 595 };
static const PusRect PUS_TXT_SEARCH = { 516, 50, 687, 75 };
// confirm dialog (window coordinates)
static const PusRect PUS_DLG = { 172, 173, 586, 502 };
static const PusRect PUS_DLG_ICON = { 247, 276, 286, 315 };
static const PusRect PUS_DLG_NAME = { 302, 282, 481, 298 }, PUS_DLG_QTY = { 302, 298, 482, 314 }, PUS_DLG_PRICE = { 256, 266, 527, 282 }, PUS_DLG_COUNT = { 373, 343, 416, 359 };
static const PusRect PUS_DLG_UP = { 414, 339, 437, 363 }, PUS_DLG_DOWN = { 351, 339, 374, 363 }, PUS_DLG_OK = { 249, 432, 360, 460 }, PUS_DLG_CANCEL = { 400, 431, 511, 460 };
