// Generated by build_rce_assets.py from re_rightclickexchange.uif -- do not edit by hand.
#pragma once
#ifndef RCE_TYPES
#define RCE_TYPES
struct RceRect { int l, t, r, b; };
struct RceSprite { const char* name; RceRect rc; };
#endif
static const int RCE_W = 602, RCE_H = 689;
static const int RCE_SLOT_COUNT = 25;
static const RceSprite RCE_SPRITES[] = {
    { "bg", { 0, 0, 602, 689 } },
    { "coupon", { 118, 80, 163, 123 } },
    { "exchange_n", { 74, 604, 258, 641 } },
    { "exchange_d", { 74, 604, 258, 641 } },
    { "exchange_o", { 74, 604, 258, 641 } },
    { "close_n", { 331, 604, 515, 638 } },
    { "close_d", { 331, 604, 515, 638 } },
    { "close_o", { 331, 604, 515, 638 } },
};
static const RceRect RCE_COUPON = { 120, 81, 159, 123 };
static const RceRect RCE_TITLE = { 195, 85, 524, 119 };  // Calibri h16 color FFFFFFFF
static const RceRect RCE_BTN_EXCHANGE = { 74, 604, 258, 641 };
static const RceRect RCE_BTN_CLOSE = { 331, 604, 515, 638 };
static const RceRect RCE_SLOTS[25] = {
    { 79, 188, 124, 234 },
    { 179, 188, 223, 234 },
    { 279, 188, 323, 234 },
    { 379, 188, 423, 234 },
    { 479, 188, 523, 234 },
    { 78, 268, 124, 316 },
    { 178, 268, 224, 316 },
    { 278, 268, 324, 316 },
    { 378, 268, 424, 316 },
    { 478, 268, 524, 316 },
    { 79, 349, 123, 393 },
    { 179, 349, 223, 393 },
    { 279, 349, 323, 393 },
    { 379, 349, 423, 393 },
    { 479, 349, 523, 393 },
    { 79, 428, 124, 474 },
    { 179, 428, 224, 474 },
    { 279, 428, 324, 474 },
    { 379, 428, 424, 474 },
    { 479, 428, 524, 474 },
    { 78, 508, 124, 555 },
    { 178, 508, 224, 555 },
    { 278, 508, 324, 555 },
    { 378, 508, 424, 555 },
    { 478, 508, 524, 555 },
};
