// Generated by build_reconnect_assets.py -- do not edit by hand.
#pragma once
static const int RC_W = 356, RC_H = 198;
static const int RC_TITLE[4] = { 20, 16, 336, 40 };
static const int RC_TEXT[4] = { 26, 40, 330, 128 };
static const int RC_BTN_RECONNECT[4] = { 46, 136, 153, 172 };
static const int RC_BTN_EXIT[4] = { 199, 137, 305, 172 };
