// Generated by build_register_assets.py -- do not edit by hand.
#pragma once
static const int RG_W = 367, RG_H = 730, RG_BIG_W = 152, RG_BIG_H = 31;
static const int RG_TITLE[4] = { 72, 17, 295, 53 };
static const int RG_TEXT[4] = { 30, 80, 337, 112 };
static const int RG_LBL_ACCOUNT[4] = { 24, 116, 343, 147 };
static const int RG_EDIT_ACCOUNT[4] = { 55, 147, 312, 173 };
static const int RG_LBL_PASSWORD[4] = { 24, 177, 343, 208 };
static const int RG_EDIT_PASSWORD[4] = { 55, 208, 312, 234 };
static const int RG_LBL_PASSWORD2[4] = { 24, 238, 343, 269 };
static const int RG_EDIT_PASSWORD2[4] = { 55, 269, 312, 295 };
static const int RG_LBL_EMAIL[4] = { 24, 299, 343, 330 };
static const int RG_EDIT_EMAIL[4] = { 55, 330, 312, 356 };
static const int RG_LBL_PHONE[4] = { 24, 360, 343, 391 };
static const int RG_EDIT_PHONE[4] = { 55, 391, 312, 417 };
static const int RG_LBL_SEAL[4] = { 24, 421, 343, 452 };
static const int RG_EDIT_SEAL[4] = { 55, 452, 312, 478 };
static const int RG_LBL_OTP[4] = { 24, 482, 343, 513 };
static const int RG_EDIT_OTP[4] = { 55, 513, 312, 539 };
static const int RG_STATUS[4] = { 28, 541, 339, 573 };
static const int RG_BTN_CLOSE[4] = { 118, 577, 248, 608 };
static const int RG_BTN_OK[4] = { 107, 672, 260, 713 };
