// Generated by build_tag_assets.py -- do not edit by hand.
#pragma once
static const int TG_W = 356, TG_H = 330;
static const int TG_TITLE[4] = { 20, 16, 336, 40 };
static const int TG_TEXT[4] = { 26, 40, 330, 58 };
static const int TG_EDIT[4] = { 60, 62, 296, 87 };
static const int TG_PALETTE[4] = { 60, 94, 295, 224 };
static const int TG_PREVIEW[4] = { 26, 228, 330, 248 };
static const int TG_STATUS[4] = { 26, 248, 330, 266 };
static const int TG_BTN_OK[4] = { 46, 274, 153, 310 };
static const int TG_BTN_CANCEL[4] = { 203, 274, 310, 310 };
